### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by paulbardack** [sokil/php-mongo-migrator#11]
Do you have plans for adding support for PHP7?

**Comment by sokil** [comment]
This is too difficult to implement. PHP7 has new mongo extension with completely different API, so there is no ability just to add support of PHP7. Library needs to be completely overwritten to get support of new extension. Currently i'm working on it, but ETA is unknown. Sorry...

**Comment by paulbardack** [comment]
Ok, thanks!
