### ISSUE TITLE
Read variables from .env

### ISSUE THREAD

**Issue by marabesi** [sokil/php-mongo-migrator#15]
Hello guys,

I was wondering if is possible to load the variables from .env inside .yml config.

My scenarios is that I have to set twice the same database access, in the.env and .yml.

Thanks!

**Comment by marabesi** [comment]
Hello @sokil as it is a enhancement, I was think in the following solution:

(Code extracted from the class Config.php)
```
public function getLogDatabaseName($environment = null)
    {
        if (!$environment) {
            $environment = $this->getDefaultEnvironment();
        }
        
        $log = $this->config['environments'][$environment]['log_database'];
        
        if ($log[0] === '%' && $log[strlen($log) - 1] === '%') {
            $param = str_replace('%', '', $log);

            return getenv($param);
        }

        return $log;
    }
```

Basically if, the yml file has an value that starts and ends with `%`, instead of simple read the value we parse it and then invoke the getenv param to get the value.

As the lib has unit tests, it will be really simple to change throughout the project.

**Comment by sokil** [comment]
Good idea, but non well implementation.Extracting     of env variables must be in one please, and this code adds parsing to all helper methods. See branch 'env', it already covers all values. 

Format of placeholder is like in symfony %env(VARNAME)%

**Comment by marabesi** [comment]
while I was searching about env + yml files, I saw the symfony approach and seems to be a good standard to follow.

I just submitted my idea to see if it was worth implementing it in the way I was thinking of(I would refactor to fetch the config value from one place for sure), but as you PR covers everything I am going to close this one and wait the new version :D

**Comment by sokil** [comment]
Check version https://github.com/sokil/php-mongo-migrator/releases/tag/0.6.0
