### ISSUE TITLE
Migrate reset

### ISSUE THREAD

**Issue by marabesi** [sokil/php-mongo-migrator#23]
Is there a way to reset all the migrations created in the database?

The readme says that is possible to rollback to a specific version, but what I wouldm like to do is to reset all the migrations and execute them again.

**Comment by sokil** [comment]
Rollback available only to specified or previous version. You can't rollback all migrations without specifying revision. Migration available to specified version or latest version.

**Comment by marabesi** [comment]
Ok I got it, probably I should send a PR implementing this feature?

**Comment by sokil** [comment]
You should not, but you may )))
