### ISSUE TITLE
Не передается environment для Manager::getDefaultDatabaseName()

### ISSUE THREAD

**Issue by paul-nebo** [sokil/php-mongo-migrator#5]
В файле Sokil\Mongo\Migrator\Manager на 52 строчке не передается environment, из-за чего всегда используется БД по-умолчанию.
Фиксится добавлением одной переменной: 
$this->_client[$environment]->useDatabase($this->_config->getDefaultDatabaseName($environment));

Слава Украине!

**Comment by sokil** [comment]
Виправлено в v.0.1.7. 

Героям слава!
