### ISSUE TITLE
Configurations option.

### ISSUE THREAD

**Issue by bobbygrossmann** [sokil/php-mongo-migrator#7]
Hi i'm not using yaml extension in my framework and it would be nice if people can decide if they want . yaml or simple array. Im comparing migration scripts and i like your setup but would be happy if i don't need to create a .yaml file.

**Comment by sokil** [comment]
PHP confuguration now supported. Please, check it. Thank you

**Comment by sokil** [comment]
Implememted.

Use 
```
mongo-migrator init --configFormat=php
```
